services:
  frontend:
    container_name: vue-frontend-prod
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '8080:80'
  backend:
    container_name: backend-prod
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '3003:3003'